# Generated by Django 4.1.5 on 2023-02-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_paypal',
            name='paypal_mail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
