# Generated by Django 4.1.6 on 2023-03-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_user_paypal_paypal_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_delivery_address',
            old_name='delivery_plz',
            new_name='delivery_zip_code',
        ),
        migrations.RenameField(
            model_name='user_payment_address',
            old_name='payment_plz',
            new_name='payment_zip_code',
        ),
    ]
