# Generated by Django 4.1.5 on 2023-02-18 17:24

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('payed', models.BooleanField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='profiles.user_delivery_address')),
                ('payment_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_address', to='profiles.user_payment_address')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('Payment_Method_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=100)),
                ('method_fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=800)),
                ('product_image_path', models.ImageField(upload_to='webshop/static/images')),
                ('price', models.FloatField()),
                ('date_last_change', models.DateField(auto_now=True)),
                ('delivery_time', models.PositiveIntegerField(verbose_name=builtins.min)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Products_per_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.PositiveIntegerField()),
                ('product_price_at_order_time', models.FloatField()),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_the_order', to='shop.order')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.payment_method'),
        ),
        migrations.AddField(
            model_name='order',
            name='products_per_order',
            field=models.ManyToManyField(through='shop.Products_per_Order', to='shop.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('Delivery_Address_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='profiles.user_delivery_address')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverys_order_id', to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_amount', models.PositiveIntegerField()),
                ('Customer_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.product')),
            ],
        ),
    ]
