# Generated by Django 4.1.5 on 2023-01-31 16:32

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('Address_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('plz', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('Delivery_Address_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='shop.address')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('payed', models.BooleanField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('delivery', models.ManyToManyField(related_name='delivery', through='shop.Delivery', to='shop.address')),
                ('payment_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_address', to='shop.address')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Method',
            fields=[
                ('Payment_Method_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=100)),
                ('method_fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=800)),
                ('product_image_path', models.ImageField(upload_to='products/')),
                ('price', models.FloatField()),
                ('date_last_change', models.DateField(auto_now=True)),
                ('delivery_time', models.PositiveIntegerField(verbose_name=builtins.min)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_amount', models.PositiveIntegerField()),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('Warehouse_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('address_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.address')),
                ('product_availability', models.ManyToManyField(through='shop.Product_Availability', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Products_per_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.PositiveIntegerField()),
                ('product_price_at_order_time', models.FloatField()),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_the_order', to='shop.order')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liking_customer', to='shop.customer')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='product_availability',
            name='Warehouse_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_warehouse', to='shop.warehouse'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.payment_method'),
        ),
        migrations.AddField(
            model_name='order',
            name='products_per_order',
            field=models.ManyToManyField(through='shop.Products_per_Order', to='shop.product'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='Order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverys_order_id', to='shop.order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.warehouse'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(related_name='cart', through='shop.Cart', to='shop.product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_billing_address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_billing_address', to='shop.address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_delivery_address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_delivery_address', to='shop.address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_payment_method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.payment_method'),
        ),
        migrations.AddField(
            model_name='customer',
            name='product_likes',
            field=models.ManyToManyField(related_name='likes', through='shop.Product_Likes', to='shop.product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='shop.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.product'),
        ),
    ]
