# Generated by Django 4.1.5 on 2023-02-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Selected',
            field=models.BooleanField(default=False),
        ),
    ]
