# Generated by Django 4.1.5 on 2023-02-16 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_customer_cart_alter_cart_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Product_ID',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.product'),
        ),
    ]
