# Generated by Django 4.1.5 on 2023-02-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_cart_product_id_cart_product_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Likes',
        ),
    ]
